### ISSUE TITLE
NuGet package ET4W.ttinclude lacks update for WriteEventSource in v1.0.0 published on 10/18/2016

### ISSUE THREAD

**Issue by brianstringfellow** [ohadschn/ET4W#1]
I installed the NuGet into a new project and the ET4W.ttinclude file doesn't contain the expected method signature. The file I have contains:
private void WriteEventSource(string eventsFile, string nameSpace, string baseTypeFullyQualifiedName = null)

**Comment by ohadschn** [comment]
You mean the `useMicrosoftDiagnosticsTracing` parameter is missing?

**Comment by brianstringfellow** [comment]
Yes, the parameter is missing.

I double checked by manually downloading the package from [https://www.nuget.org/api/v2/package/OhadSoft.ET4W/1.0.0](url), opened the .nuppkg file with 7-Zip, and examined the 'ET4W.ttinclude' file in 'ohadsoft.et4w.1.0.0.nupkg\content\ET4W\'.

The first few lines containing the method are as:
<#@ assembly name="System.Core"#>
<#@ assembly name="System.Xml"#>
<#@ assembly name="System.Runtime.Serialization"#>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Text"#>
<#@ import namespace="System.Collections.Generic"#>
<#@ import namespace="System.Runtime.Serialization" #>
<#@ import namespace="System.Runtime.Serialization.Json" #>
<#@ import namespace="System.Diagnostics.Tracing" #>
<#@ import namespace="System.Globalization" #>
<#+
private void WriteEventSource(string eventsFile, string nameSpace, string baseTypeFullyQualifiedName = null)
{
	baseTypeFullyQualifiedName = baseTypeFullyQualifiedName ?? typeof(EventSource).FullName;
	EventDefinitions eventDefinitions = null;
	var dcjs = new DataContractJsonSerializer(typeof(EventDefinitions));

	//we don't use FileStream directly below in order to support UTF BOM headers
	using (var eventsStream = new MemoryStream(Encoding.UTF8.GetBytes(File.ReadAllText(eventsFile))))
    {
		eventDefinitions = (EventDefinitions)dcjs.ReadObject(eventsStream);
    }
	ValidateEventDefinitions(eventDefinitions);
	var eventClassName = eventDefinitions.Class + "Events"; 
	var eventSourceClassName = eventDefinitions.Class + "EventSource"; 
	var customTypeTargets = eventDefinitions.CustomTypes.ToDictionary(ct => ct.FullyQualifiedName, ct => ct.TargetType);
#>

**Comment by ohadschn** [comment]
Thank you for letting me know. Is this just an FYI or do you actually need this feature?

**Comment by brianstringfellow** [comment]
Mostly an FYI. I am exploring ways to simplify creating ETW classes, especially for dependent application developers that aren't so familiar with writing the classes and methods. ET4W caught my attention as a simpler way to create the classes. One thing in particular we want is a way to specify a base or required schema (e.g. for auditing) and allow applications to augment with additional properties.

**Comment by ohadschn** [comment]
What you mean by "base or required schema (e.g. for auditing) and allow applications to augment with additional properties"? Could you provide a code snippet that demonstrates what you want to achieve?

**Comment by brianstringfellow** [comment]
The ability to specify 'commonParameters' is what I was referring to by 'base or required schema'. We want every event to have a SessionId, CorrelationId, ActivityId, UserId, etc., similar to what you have in 'variedEvents.json'.

**Comment by ohadschn** [comment]
Great minds think alike ;)
