### ISSUE TITLE
Building in VS 2017

### ISSUE THREAD

**Issue by brianstringfellow** [ohadschn/ET4W#2]
Do you know of any specific settings or extensions that may be needed to get the solution to build in Visual Studio 2017?

I cloned the project and loaded the solution in VS 2017 and got the following errors:
```
1>------ Build started: Project: Tests, Configuration: Debug Any CPU ------
2>------ Build started: Project: NugetTests, Configuration: Debug Any CPU ------
1>c:\GitRepos\FromInternet\ET4W\src\ET4W.ttinclude(158,85): error CS0103: Compiling transformation: The name 'nameof' does not exist in the current context
1>c:\GitRepos\FromInternet\ET4W\src\ET4W.ttinclude(158,92): error CS0118: Compiling transformation: 'System.Diagnostics.Tracing.EventLevel' is a 'type' but is used like a 'variable'
1>C:\GitRepos\FromInternet\ET4W\src\packages\Clarius.TransformOnBuild.1.1.12\build\Clarius.TransformOnBuild.targets(45,9): error MSB3073: The command ""C:\Program Files (x86)\Common Files\Microsoft Shared\TextTemplating\14.0\TextTransform.exe" "C:\GitRepos\FromInternet\ET4W\src\Tests\Events\variedEvents.tt"" exited with code 1.
2>c:\GitRepos\FromInternet\ET4W\src\NugetTests\ET4W\ET4W.ttinclude(150,85): error CS0103: Compiling transformation: The name 'nameof' does not exist in the current context
2>c:\GitRepos\FromInternet\ET4W\src\NugetTests\ET4W\ET4W.ttinclude(150,92): error CS0118: Compiling transformation: 'System.Diagnostics.Tracing.EventLevel' is a 'type' but is used like a 'variable'
2>C:\GitRepos\FromInternet\ET4W\src\packages\Clarius.TransformOnBuild.1.1.12\build\Clarius.TransformOnBuild.targets(45,9): error MSB3073: The command ""C:\Program Files (x86)\Common Files\Microsoft Shared\TextTemplating\14.0\TextTransform.exe" "C:\GitRepos\FromInternet\ET4W\src\NugetTests\events.tt"" exited with code 1.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

I was able to open the solution in VS 2015 and get a successful build. The reason I ask about using VS 2017 is because our team is currently developing with that version of the IDE.

**Comment by ohadschn** [comment]
I think it's an issue with _Clarius.TransformOnBuild_, which this workaround should resolve:
https://github.com/clariuslabs/TransformOnBuild/issues/42#issuecomment-296131420

As the author noted though, he has moved on to `Mono.TextTemplating` which I'll do as well. My current machine only has VS2017 so rest assured I will make it work there. I'll try to get to it in the next few days.

**Comment by ohadschn** [comment]
Hmm actually that output (and you comment) suggests you have VS2015 installed which means the `TextTransform.exe` is found. I think yours might be another issue: https://www.teamdevelopmentforsitecore.com/Blog/t4-transform-file-problems-code-gen. Also see https://stackoverflow.com/questions/23281434/t4-reports-compiling-transformation-invalid-token-this-in-class-struct.

**Comment by brianstringfellow** [comment]
I saw you updated the projects. I pulled the latest and the solution now builds. Thanks!

**Comment by ohadschn** [comment]
Sure thing!
